name: Release Latest

on:
  workflow_dispatch:
    inputs:
      BUILD:
        description: "Build Packages"
        type: boolean
        default: true

      SIGN:
        description: "Sign Packages"
        type: boolean
        default: true

      ARCHIVE-PACKAGES:
        description: "Archive Packages"
        type: boolean
        default: false

      UPLOAD:
        description: "Upload Packages"
        type: boolean
        default: true

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@main
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Declare Variables
      run: |
        echo "MAIN_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

    - name: Download Integrations
      uses: robinraju/release-downloader@main
      with: 
        repository: "revanced/revanced-integrations"
        latest: true
        fileName: "*.apk"
        out-file-path: "revanced/assets/temp/integrations"

    - name: Download CLI
      uses: robinraju/release-downloader@main
      with: 
        repository: "revanced/revanced-cli"
        latest: true
        fileName: "*.jar"
        out-file-path: "revanced/assets/temp/cli"

    - name: Download Patches
      uses: robinraju/release-downloader@main
      with: 
        repository: "revanced/revanced-patches"
        latest: true
        fileName: "*.jar"
        out-file-path: "revanced/assets/temp/patches"

    - name: Copy Files
      run: |
        cd revanced
        chmod +x copy.latest.files.sh
        ./copy.latest.files.sh

    - name: Download Icon Pack Studio
      if: inputs.BUILD
      run: |
        cd revanced/packages/icon.pack.studio
        chmod +x download.sh
        ./download.sh

    - name: Compile Icon Pack Studio
      if: inputs.BUILD
      run: |
        cd revanced/packages/icon.pack.studio
        chmod +x compile.sh
        ./compile.sh

    - name: Download Micro G
      if: inputs.BUILD
      uses: robinraju/release-downloader@main
      with: 
        repository: "inotia00/VancedMicroG"
        latest: true
        fileName: "*.apk"
        out-file-path: "revanced/packages/micro-g"

    - name: Download Nyx Music Player
      if: inputs.BUILD
      run: |
        cd revanced/packages/nyx
        chmod +x download.sh
        ./download.sh

    - name: Compile Nyx Music Player
      if: inputs.BUILD
      run: |
        cd revanced/packages/nyx
        chmod +x compile.sh
        ./compile.sh

    - name: Download Reddit
      if: inputs.BUILD
      run: |
        cd revanced/packages/reddit
        chmod +x download.sh
        ./download.sh

    - name: Compile Reddit
      if: inputs.BUILD
      run: |
        cd revanced/packages/reddit
        chmod +x compile.sh
        ./compile.sh

    - name: Download ReVanced Manager
      if: inputs.BUILD
      uses: robinraju/release-downloader@main
      with: 
        repository: "revanced/revanced-manager"
        latest: true
        fileName: "*.apk"
        out-file-path: "revanced/packages/manager"

    - name: Download Spotify
      if: inputs.BUILD
      run: |
        cd revanced/packages/spotify
        chmod +x download.sh
        ./download.sh

    - name: Compile Spotify
      if: inputs.BUILD
      run: |
        cd revanced/packages/spotify
        chmod +x compile.sh
        ./compile.sh

    - name: Download TikTok
      if: inputs.BUILD
      run: |
        cd revanced/packages/tiktok
        chmod +x download.sh
        ./download.sh

    - name: Compile TikTok
      if: inputs.BUILD
      run: |
        cd revanced/packages/tiktok
        chmod +x compile.sh
        ./compile.sh

    - name: Download Twitch
      if: inputs.BUILD
      run: |
        cd revanced/packages/twitch
        chmod +x download.sh
        ./download.sh

    - name: Compile Twitch
      if: inputs.BUILD
      run: |
        cd revanced/packages/twitch
        chmod +x compile.sh
        ./compile.sh

    - name: Download Twitter
      if: inputs.BUILD
      run: |
        cd revanced/packages/twitter
        chmod +x download.sh
        ./download.sh

    - name: Compile Twitter
      if: inputs.BUILD
      run: |
        cd revanced/packages/twitter
        chmod +x compile.sh
        ./compile.sh

    - name: Download YouTube Music arm-v7a
      if: inputs.BUILD
      run: |
        cd revanced/packages/youtube.music/v7a
        chmod +x download.sh
        ./download.sh

    - name: Compile YouTube Music arm-v7a
      if: inputs.BUILD
      run: |
        cd revanced/packages/youtube.music/v7a
        chmod +x compile.sh
        ./compile.sh experimental

    - name: Download YouTube Music arm64-v8a
      if: inputs.BUILD
      run: |
        cd revanced/packages/youtube.music/v8a
        chmod +x download.sh
        ./download.sh

    - name: Compile YouTube Music arm64-v8a
      if: inputs.BUILD
      run: |
        cd revanced/packages/youtube.music/v8a
        chmod +x compile.sh
        ./compile.sh experimental

    - name: Download YouTube
      if: inputs.BUILD
      run: |
        cd revanced/packages/youtube
        chmod +x download.sh
        ./download.sh

    - name: Compile YouTube
      if: inputs.BUILD
      run: |
        cd revanced/packages/youtube
        chmod +x compile.sh
        ./compile.sh experimental

    - name: Sign Packages
      if: inputs.SIGN
      run: |
        cd revanced
        chmod +x sign.sh
        ./sign.sh

    - name: Archive Packages
      if: inputs.ARCHIVE-PACKAGES
      run: |
        cd revanced
        chmod +x 7z.sh
        ./7z.sh

    - name: Upload ReVanced Applications
      if: inputs.UPLOAD
      uses: termux/upload-release-action@master
      with:
        repo_name: SCPF-Archive/repo.1
        repo_token: ${{ secrets.REPO_TOKEN }}
        release_name: "${{ github.run_id }}"
        tag: "${{ env.MAIN_TAG }}"
        file: revanced/packages/latest/app/*
        overwrite: true
        file_glob: true
        prerelease: false
